trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    displayName: 'Build and Deploy'
    steps:
      - checkout: self

      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'

      - script: |
          npm ci
          npm run build --if-present
          npm run test --if-present

      - task: ArchiveFiles@2
        displayName: 'Archive Files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Artifact'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          artifactName: 'dist'

      - task: AzureWebApp@1
        displayName: 'Azure Web App Deploy'
        inputs:
          appType: webAppLinux
          azureSubscription: 'Trainsquare - Microsoft Azure Sponsorship (dd1c0dde-bf25-496d-9c2e-adecb45809d1)'
          appName: 'trainsquareBackOffice'  # Update with the name of your Azure App Service
          package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          deploymentMethod: 'runFromPackage'

